# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/135nOU0NFBDW6CzuvJiQkLCqQWjolVtm3
"""

import math
import os

class TicTacToe:
    def __init__(self):
        self.board = [' ' for _ in range(9)]
        self.stats = {'AI': 0, 'Human': 0, 'Draws': 0}

    def print_board(self):
        os.system('cls' if os.name == 'nt' else 'clear')
        print(f" AI: {self.stats['AI']} | Human: {self.stats['Human']} | Draws: {self.stats['Draws']}\n")
        for i in range(0, 9, 3):
            print(f" {self.board[i]} | {self.board[i+1]} | {self.board[i+2]} ")
            if i < 6: print("-----------")

    def available_moves(self):
        return [i for i, spot in enumerate(self.board) if spot == ' ']

    def check_winner(self, board, player):
        win_conf = [(0,1,2), (3,4,5), (6,7,8), (0,3,6), (1,4,7), (2,5,8), (0,4,8), (2,4,6)]
        return any(all(board[i] == player for i in combo) for combo in win_conf)

    def is_board_full(self):
        return ' ' not in self.board

    def minimax(self, board, depth, is_maximizing):
        # Base Cases: Terminal States
        if self.check_winner(board, 'O'): return 10 - depth
        if self.check_winner(board, 'X'): return depth - 10
        if ' ' not in board: return 0

        if is_maximizing:
            best_score = -math.inf
            for move in [i for i, s in enumerate(board) if s == ' ']:
                board[move] = 'O'
                score = self.minimax(board, depth + 1, False)
                board[move] = ' '
                best_score = max(score, best_score)
            return best_score
        else:
            best_score = math.inf
            for move in [i for i, s in enumerate(board) if s == ' ']:
                board[move] = 'X'
                score = self.minimax(board, depth + 1, True)
                board[move] = ' '
                best_score = min(score, best_score)
            return best_score

    def get_best_move(self):
        best_score = -math.inf
        move = None
        for i in self.available_moves():
            self.board[i] = 'O'
            score = self.minimax(self.board, 0, False)
            self.board[i] = ' '
            if score > best_score:
                best_score = score
                move = i
        return move

    def play(self):
        while True:
            self.board = [' ' for _ in range(9)]
            user_turn = True # Human starts as X

            while True:
                self.print_board()
                if self.check_winner(self.board, 'O'):
                    self.stats['AI'] += 1
                    print("\nAI Wins! (As expected.)")
                    break
                if self.check_winner(self.board, 'X'):
                    self.stats['Human'] += 1
                    print("\nYou won? This shouldn't happen!")
                    break
                if self.is_board_full():
                    self.stats['Draws'] += 1
                    print("\nIt's a Draw!")
                    break

                if user_turn:
                    try:
                        move = int(input("\nYour move (0-8): "))
                        if self.board[move] != ' ': raise ValueError
                        self.board[move] = 'X'
                        user_turn = False
                    except:
                        print("\nInvalid move. Try again.")
                else:
                    print("AI is thinking...")
                    move = self.get_best_move()
                    self.board[move] = 'O'
                    user_turn = True

            if input("\nPlay again? (y/n): ").lower() != 'y':
                break

if __name__ == "__main__":
    game = TicTacToe()
    game.play()
